# This workflow will install Python dependencies, run tests, run linting, and test building docs
name: Building Docs

on:
  workflow_call: # Reusing the workflow for other workflows


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pip setuptools wheel --upgrade
        python -m pip install -e .[docs]
    - name: Build docs
      working-directory: ./docs
      run: make html